//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.22 at 02:30:42 AM ICT 
//


package carogameservice.ws;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the carogameservice.ws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: carogameservice.ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link KhoiTaoBanCoRequest }
     * 
     */
    public KhoiTaoBanCoRequest createKhoiTaoBanCoRequest() {
        return new KhoiTaoBanCoRequest();
    }

    /**
     * Create an instance of {@link KhoiTaoBanCoResponse }
     * 
     */
    public KhoiTaoBanCoResponse createKhoiTaoBanCoResponse() {
        return new KhoiTaoBanCoResponse();
    }

    /**
     * Create an instance of {@link BanCo }
     * 
     */
    public BanCo createBanCo() {
        return new BanCo();
    }

    /**
     * Create an instance of {@link KiemTraTinhHopLeRequest }
     * 
     */
    public KiemTraTinhHopLeRequest createKiemTraTinhHopLeRequest() {
        return new KiemTraTinhHopLeRequest();
    }

    /**
     * Create an instance of {@link KiemTraTinhHopLeResponse }
     * 
     */
    public KiemTraTinhHopLeResponse createKiemTraTinhHopLeResponse() {
        return new KiemTraTinhHopLeResponse();
    }

    /**
     * Create an instance of {@link QuanCo }
     * 
     */
    public QuanCo createQuanCo() {
        return new QuanCo();
    }

    /**
     * Create an instance of {@link KiemTraThangRequest }
     * 
     */
    public KiemTraThangRequest createKiemTraThangRequest() {
        return new KiemTraThangRequest();
    }

    /**
     * Create an instance of {@link KiemTraThangResponse }
     * 
     */
    public KiemTraThangResponse createKiemTraThangResponse() {
        return new KiemTraThangResponse();
    }

    /**
     * Create an instance of {@link Player }
     * 
     */
    public Player createPlayer() {
        return new Player();
    }

}
