//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.22 at 02:30:42 AM ICT 
//


package carogameservice.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QuanCo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QuanCo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="hang" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="cot" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QuanCo", propOrder = {
    "hang",
    "cot",
    "type"
})
public class QuanCo {

    protected int hang;
    protected int cot;
    @XmlElement(required = true)
    protected String type;

    /**
     * Gets the value of the hang property.
     * 
     */
    public int getHang() {
        return hang;
    }

    /**
     * Sets the value of the hang property.
     * 
     */
    public void setHang(int value) {
        this.hang = value;
    }

    /**
     * Gets the value of the cot property.
     * 
     */
    public int getCot() {
        return cot;
    }

    /**
     * Sets the value of the cot property.
     * 
     */
    public void setCot(int value) {
        this.cot = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
